apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: assessment-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "WARN"