apiVersion: v1
kind: ConfigMap
metadata:
  name: assessment-service-config
  namespace: default
  labels:
    app: assessment-service
data:
  # Application Configuration
  PORT: "8080"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"

  # Database Configuration
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "assessment_db"
  DB_USER: "assessment_user"
  DB_SSL_MODE: "require"

  # Redis Configuration
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  REDIS_DB: "0"

  # Casdoor Configuration
  CASDOOR_ENDPOINT: "https://casdoor.example.com"
  CASDOOR_ORGANIZATION: "assessment-org"
  CASDOOR_APPLICATION: "assessment-app"

  # Health Check Configuration
  HEALTH_CHECK_PATH: "/health"

  # CORS Configuration
  CORS_ALLOWED_ORIGINS: "*"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Content-Type,Authorization"

  # File Upload Configuration
  MAX_UPLOAD_SIZE: "10MB"
  UPLOAD_PATH: "/uploads"

  # Timezone
  TZ: "Asia/Ho_Chi_Minh"