apiVersion: v1
kind: Secret
metadata:
  name: assessment-service-secret
  namespace: default
  labels:
    app: assessment-service
type: Opaque
stringData:
  # Database connection string
  DATABASE_URL: ""

  # Redis connection string
  REDIS_URL: ""

  # Casdoor configuration
  CASDOOR_CLIENT_ID: ""
  CASDOOR_CLIENT_SECRET: ""
  CASDOOR_CERT: ""