apiVersion: v1
kind: Service
metadata:
  name: assessment-service
  namespace: default
  labels:
    app: assessment-service
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: assessment-service
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: assessment-service-ingressroute
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`assessment.m3xd.dev`)
      kind: Rule
      services:
        - name: assessment-service
          port: 80
  tls:
    secretName: m3xd-dev-tls