apiVersion: apps/v1
kind: Deployment
metadata:
  name: assessment-service
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: assessment-service
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "WARN"
        - name: GIN_MODE
          value: "release"