apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base configuration
resources:
- ../../

# Namespace for production
namespace: assessment-prod

# Name prefix for production resources
namePrefix: prod-

# Production-specific image tag
images:
- name: assessment-service
  newName: your-registry/assessment-service
  newTag: v1.0.0

# Production patches
patchesStrategicMerge:
- deployment-patch.yaml
- hpa-patch.yaml

# Production configmap
configMapGenerator:
- name: assessment-service-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=WARN
  - REPLICAS=5

# Production secrets (should be encrypted with SOPS or sealed-secrets)
secretGenerator:
- name: assessment-service-secret
  behavior: replace
  files:
  - DATABASE_URL=secrets/database-url
  - JWT_SECRET=secrets/jwt-secret
  - REDIS_URL=secrets/redis-url